---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-k3s-prod
    env: prod
    owner: admin
spec:
  selector:
    project: demo 
  ports:
  - name: listener
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer