apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: my-k3s-prod
    env: prod
    owner: admin
spec:
  selector:
    project: demo-rst
  ports:
  - name: {{ .Release.Name }}-listener
    protocol: TCP
    port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
  type: LoadBalancer
