apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: containers-nginx
      image: kerne1paniiccc/simple_app_for_test_devops:latest
      ports:
        - containerPort: 8000