[master]
master ansible_host=192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=/home/kali/Projects-git/DevSecOps-Docker-img/kubernetes-advanced/k3s-vagrant-cluster/Vagrant-cluster/.vagrant/machines/master/libvirt/private_key

[worker]
worker ansible_host=192.168.56.11 ansible_user=vagrant ansible_ssh_private_key_file=/home/kali/Projects-git/DevSecOps-Docker-img/kubernetes-advanced/k3s-vagrant-cluster/Vagrant-cluster/.vagrant/machines/worker/libvirt/private_key
